def numstr2num(numstr: str) -> float:
    if numstr is None:
        return None
    temp = numstr
    temp = temp.replace(",", "")
    temp = float(temp)
    return temp

country2region = {
    "China": "East Asia",
    "Japan": "East Asia",
    "South Korea": "East Asia",
    "Taiwan": "East Asia",
    "Hong Kong": "East Asia",
    "Macau": "East Asia",
    "Mongolia": "East Asia",
    "North Korea": "East Asia",
    "Indonesia": "Southeast Asia",
    "Thailand": "Southeast Asia",
    "Vietnam": "Southeast Asia",
    "Malaysia": "Southeast Asia",
    "Philippines": "Southeast Asia",
    "Singapore": "Southeast Asia",
    "Myanmar": "Southeast Asia",
    "Cambodia": "Southeast Asia",
    "Laos": "Southeast Asia",
    "Brunei": "Southeast Asia",
    "East Timor": "Southeast Asia",
    "India": "South Asia",
    "Pakistan": "South Asia",
    "Bangladesh": "South Asia",
    "Sri Lanka": "South Asia",
    "Nepal": "South Asia",
    "Afghanistan": "South Asia",
    "Maldives": "South Asia",
    "Bhutan": "South Asia",
    "Kazakhstan": "Central Asia",
    "Uzbekistan": "Central Asia",
    "Turkmenistan": "Central Asia",
    "Kyrgyzstan": "Central Asia",
    "Tajikistan": "Central Asia",
    "Germany": "Western Europe",
    "United Kingdom": "Western Europe",
    "France": "Western Europe",
    "Italy": "Western Europe",
    "Spain": "Western Europe",
    "Netherlands": "Western Europe",
    "Switzerland": "Western Europe",
    "Belgium": "Western Europe",
    "Sweden": "Western Europe",
    "Ireland": "Western Europe",
    "Austria": "Western Europe",
    "Norway": "Western Europe",
    "Denmark": "Western Europe",
    "Finland": "Western Europe",
    "Portugal": "Western Europe",
    "Greece": "Western Europe",
    "Luxembourg": "Western Europe",
    "Iceland": "Western Europe",
    "Malta": "Western Europe",
    "Monaco": "Western Europe",
    "Andorra": "Western Europe",
    "San Marino": "Western Europe",
    "Liechtenstein": "Western Europe",
    "Russia": "Eastern Europe",
    "Poland": "Eastern Europe",
    "Romania": "Eastern Europe",
    "Czech Republic": "Eastern Europe",
    "Hungary": "Eastern Europe",
    "Ukraine": "Eastern Europe",
    "Slovakia": "Eastern Europe",
    "Bulgaria": "Eastern Europe",
    "Croatia": "Eastern Europe",
    "Lithuania": "Eastern Europe",
    "Slovenia": "Eastern Europe",
    "Latvia": "Eastern Europe",
    "Estonia": "Eastern Europe",
    "Belarus": "Eastern Europe",
    "Moldova": "Eastern Europe",
    "Bosnia and Herzegovina": "Eastern Europe",
    "Albania": "Eastern Europe",
    "North Macedonia": "Eastern Europe",
    "Montenegro": "Eastern Europe",
    "Kosovo": "Eastern Europe",
    "Turkey": "Eastern Europe",
    "Serbia": "Eastern Europe",
    "Azerbaijan": "Eastern Europe",
    "Cyprus": "Eastern Europe",
    "Georgia": "Eastern Europe",
    "Armenia": "Eastern Europe",
    "Saudi Arabia": "Middle East",
    "Iran": "Middle East",
    "United Arab Emirates": "Middle East",
    "Israel": "Middle East",
    "Iraq": "Middle East",
    "Qatar": "Middle East",
    "Kuwait": "Middle East",
    "Oman": "Middle East",
    "Jordan": "Middle East",
    "Lebanon": "Middle East",
    "Bahrain": "Middle East",
    "Syria": "Middle East",
    "Yemen": "Middle East",
    "Palestine": "Middle East",
    "United States": "North America",
    "Canada": "North America",
    "Mexico": "North America",
    "Bermuda": "North America",
    "Cayman Islands": "North America",
    "Aruba": "North America",
    "Curaçao": "North America",
    "Greenland": "North America",
    "Sint Maarten": "North America",
    "Turks and Caicos Islands": "North America",
    "Brazil": "Latin America",
    "Argentina": "Latin America",
    "Colombia": "Latin America",
    "Chile": "Latin America",
    "Peru": "Latin America",
    "Venezuela": "Latin America",
    "Ecuador": "Latin America",
    "Bolivia": "Latin America",
    "Paraguay": "Latin America",
    "Uruguay": "Latin America",
    "Cuba": "Latin America",
    "Dominican Republic": "Latin America",
    "Puerto Rico": "Latin America",
    "Panama": "Latin America",
    "Costa Rica": "Latin America",
    "Guatemala": "Latin America",
    "Honduras": "Latin America",
    "El Salvador": "Latin America",
    "Nicaragua": "Latin America",
    "Jamaica": "Latin America",
    "Trinidad and Tobago": "Latin America",
    "Bahamas": "Latin America",
    "Barbados": "Latin America",
    "Guyana": "Latin America",
    "Suriname": "Latin America",
    "Belize": "Latin America",
    "Haiti": "Latin America",
    "Saint Lucia": "Latin America",
    "Grenada": "Latin America",
    "Saint Kitts and Nevis": "Latin America",
    "Saint Vincent and the Grenadines": "Latin America",
    "Antigua and Barbuda": "Latin America",
    "Dominica": "Latin America",
    "Australia": "Oceania",
    "New Zealand": "Oceania",
    "Papua New Guinea": "Oceania",
    "Fiji": "Oceania",
    "Solomon Islands": "Oceania",
    "Vanuatu": "Oceania",
    "New Caledonia": "Oceania",
    "French Polynesia": "Oceania",
    "Samoa": "Oceania",
    "Tonga": "Oceania",
    "Micronesia": "Oceania",
    "Kiribati": "Oceania",
    "Palau": "Oceania",
    "Marshall Islands": "Oceania",
    "Nauru": "Oceania",
    "Tuvalu": "Oceania",
    "Egypt": "North Africa",
    "Algeria": "North Africa",
    "Morocco": "North Africa",
    "Tunisia": "North Africa",
    "Libya": "North Africa",
    "Nigeria": "Sub-Saharan Africa",
    "South Africa": "Sub-Saharan Africa",
    "Ethiopia": "Sub-Saharan Africa",
    "Kenya": "Sub-Saharan Africa",
    "Ghana": "Sub-Saharan Africa",
    "Angola": "Sub-Saharan Africa",
    "Tanzania": "Sub-Saharan Africa",
    "DR Congo": "Sub-Saharan Africa",
    "Sudan": "Sub-Saharan Africa",
    "Uganda": "Sub-Saharan Africa",
    "Cameroon": "Sub-Saharan Africa",
    "Ivory Coast": "Sub-Saharan Africa",
    "Madagascar": "Sub-Saharan Africa",
    "Zambia": "Sub-Saharan Africa",
    "Senegal": "Sub-Saharan Africa",
    "Zimbabwe": "Sub-Saharan Africa",
    "Guinea": "Sub-Saharan Africa",
    "Rwanda": "Sub-Saharan Africa",
    "Benin": "Sub-Saharan Africa",
    "Burkina Faso": "Sub-Saharan Africa",
    "Somalia": "Sub-Saharan Africa",
    "Mali": "Sub-Saharan Africa",
    "Malawi": "Sub-Saharan Africa",
    "Mauritius": "Sub-Saharan Africa",
    "Togo": "Sub-Saharan Africa",
    "Eswatini": "Sub-Saharan Africa",
    "Sierra Leone": "Sub-Saharan Africa",
    "Namibia": "Sub-Saharan Africa",
    "Botswana": "Sub-Saharan Africa",
    "Lesotho": "Sub-Saharan Africa",
    "Gambia": "Sub-Saharan Africa",
    "Gabon": "Sub-Saharan Africa",
    "Mauritania": "Sub-Saharan Africa",
    "Guinea-Bissau": "Sub-Saharan Africa",
    "Equatorial Guinea": "Sub-Saharan Africa",
    "Djibouti": "Sub-Saharan Africa",
    "Comoros": "Sub-Saharan Africa",
    "Cape Verde": "Sub-Saharan Africa",
    "São Tomé and Príncipe": "Sub-Saharan Africa",
    "Seychelles": "Sub-Saharan Africa",
    "Eritrea": "Sub-Saharan Africa",
    "South Sudan": "Sub-Saharan Africa",
    "Burundi": "Sub-Saharan Africa",
    "Liberia": "Sub-Saharan Africa",
    "Central African Republic": "Sub-Saharan Africa",
    "Chad": "Sub-Saharan Africa",
    "Niger": "Sub-Saharan Africa",
    "Mozambique": "Sub-Saharan Africa",
    "Congo": "Sub-Saharan Africa",
    "Zanzibar": "Sub-Saharan Africa"
}

if __name__ == "__main__":
    print(numstr2num("2,100"))




