services:
  master:
    image: hadoop:latest
    platform: linux/arm64
    container_name: master
    hostname: master
    ports:
      - "9870:9870" # NameNode HTTP UI
      - "9000:9000" # NameNode IPC
      - "8088:8088" # ResourceManager UI
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
    volumes:
      - ./db/name:/usr/local/hadoop/hdfs/namenode
    environment:
      - HADOOP_ROLE=master
      - HDFS_NAMENODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
    command: >
      /bin/bash -c "
      /start-system.sh;
      tail -f /dev/null"
    networks:
      - hadoop_network

  worker-1:
    image: hadoop:latest
    platform: linux/arm64
    container_name: worker-1
    hostname: worker-1
    ports:
      - "9861:9864"
      - "9001:9000"  # DataNode IPC
      - "8042:8042"  # NodeManager
    volumes:
      - ./db/data-1:/usr/local/hadoop/hdfs/datanode
    environment:
      - HADOOP_ROLE=worker
      - HDFS_DATANODE_USER=root
      - YARN_NODEMANAGER_USER=root
    command: >
      /bin/bash -c "
      /start-system.sh;
      tail -f /dev/null"
    networks:
      - hadoop_network

  worker-2:
    image: hadoop:latest
    platform: linux/arm64
    container_name: worker-2
    hostname: worker-2
    ports:
      - "9862:9864"
      - "9002:9000"  # DataNode IPC
      - "8043:8042"  # NodeManager
    volumes:
      - ./db/data-2:/usr/local/hadoop/hdfs/datanode
    environment:
      - HADOOP_ROLE=worker
      - HDFS_DATANODE_USER=root
      - YARN_NODEMANAGER_USER=root
    command: >
      /bin/bash -c "
      /start-system.sh;
      tail -f /dev/null"
    networks:
      - hadoop_network

  worker-3:
    image: hadoop:latest
    platform: linux/arm64
    container_name: worker-3
    hostname: worker-3
    ports:
      - "9863:9864"
      - "9003:9000"  # DataNode IPC
      - "8044:8042"  # NodeManager
    volumes:
      - ./db/data-3:/usr/local/hadoop/hdfs/datanode
    environment:
      - HADOOP_ROLE=worker
      - HDFS_DATANODE_USER=root
      - YARN_NODEMANAGER_USER=root      
    command: >
      /bin/bash -c "
      /start-system.sh;
      tail -f /dev/null"
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge
