class BaseException(Exception): ...


class QueueException(BaseException): ...


class QueueFullException(QueueException): ...


class QueueEmptyException(QueueException): ...


class ExtractorException(BaseException): ...


class ExtractorPoolException(BaseException): ...


class TransformerException(BaseException): ...


class TransformerPoolException(BaseException): ...


class LoaderException(BaseException): ...


class LoaderPoolException(BaseException): ...
