version: '3'

services:
  spark-master:
    image : spark:1.0
    container_name: spark-master 
    hostname : spark-master 
    networks:
      - spark-networks
    ports:
      - "8080:8080"
      - "7077:7077"
    command : ["/bin/bash", "-c", "/opt/spark/sbin/start-master.sh -h 0.0.0.0 && tail -f /opt/spark/logs/spark--*.out"]
  spark-worker-1:
    image : spark:1.0
    container_name: spark-worker-1
    hostname : spark-worker-1
    networks:
      - spark-networks
    depends_on:
      - spark-master
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/spark--*.out"]
  spark-worker-2:
    image : spark:1.0
    container_name: spark-worker-2
    hostname : spark-worker-2
    networks:
      - spark-networks
    depends_on:
      - spark-master
    command: ["/bin/bash", "-c", "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/spark--*.out"]
networks:
  spark-networks:
    driver: bridge