version: "3"
services:
  master:
    build:
      context: ./master
      args:
        HADOOP_USER_PWD: ${HADOOP_USER_PWD}
    container_name: hadoop-master
    hostname: master
    environment:
      - HADOOP_ROLE=master
      - HADOOP_DATANODE_HOSTNAME=master
    ports:
      - "9870:9870" # HDFS NameNode UI
      - "8088:8088" # YARN ResourceManager UI
      - "8032:8032" # YARN ResourceManager UI
    networks:
      - hadoop-network
    volumes:
      - hdfs-name-node:/hadoop/dfs/name
  worker1:
    build:
      context: worker
      args:
        HADOOP_USER_PWD: ${HADOOP_USER_PWD}
    container_name: hadoop-worker1
    hostname: worker1
    environment:
      - HADOOP_ROLE=worker1
      - HADOOP_DATANODE_HOSTNAME=worker1
#    ports:
#      - "9864:9864"
    depends_on:
      - master
    networks:
      - hadoop-network
    volumes:
      - hdfs-data-node1:/hadoop/dfs/data
  worker2:
    build:
      context: worker
      args:
        HADOOP_USER_PWD: ${HADOOP_USER_PWD}
    container_name: hadoop-worker2
    hostname: worker2
    environment:
      - HADOOP_ROLE=worker2
      - HADOOP_DATANODE_HOSTNAME=worker2
#    ports:
#      - "9864:9864"
    depends_on:
      - master
    networks:
      - hadoop-network
    volumes:
      - hdfs-data-node2:/hadoop/dfs/data
networks:
  hadoop-network:
    driver: bridge

volumes:
  hdfs-name-node:
  hdfs-data-node1:
  hdfs-data-node2: