version: '3'
services:
  namenode:
    image: hadoop-base:latest
    user: hduser
    volumes:
      - hadoop_namenode1:/hadoop/dfs/name
    ports:
      - "9870:9870" # HDFS Web UI
      - "8020:8020" # RPC
      - "8088:8088" # Yarn WEB UI
      - "9000:9000" # HDFS IPC
      # - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
    hostname: namenode
    container_name: namenode
    # command: ["/bin/bash"]  # namenode 컨테이너 실행 시 실행할 명령어.
    command: ["./namenode-entrypoint.sh"]  # namenode 컨테이너 실행 시 실행할 명령어.
    networks:
      - hadoop_network
        
  datanode1:
    image: hadoop-base:latest
    user: hduser
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      # 다른 볼륨 설정...
    container_name: datanode1
    depends_on:
      - namenode
    # command: ["/bin/bash"]  # datanode 컨테이너 실행 시 실행할 명령어.
    command: ["./datanode-entrypoint.sh"]  # datanode 컨테이너 실행 시 실행할 명령어.
    networks:
      - hadoop_network

  datanode2:
    container_name: datanode2   
    user: hduser
    image: hadoop-base:latest
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    # command: [""]  # datanode 컨테이너 실행 시 실행할 명령어.
    depends_on:
      - namenode
    command: ["./datanode-entrypoint.sh"]  # datanode 컨테이너 실행 시 실행할 명령어.
    networks:
      - hadoop_network

volumes:
  hadoop_namenode1:
  hadoop_datanode1:
  hadoop_datanode2:

networks:
  hadoop_network:
    driver: bridge
  