FROM ubuntu:20.04

# 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk ssh sudo vim && \
    apt-get clean

# 리눅스 하둡 유저 생성 - 비밀번호 1111, 쉘 배쉬로 설정, 수도 명령어 권한 부여
RUN useradd -d /home/hadoop/ -m -p 1111 -s /bin/bash hadoop && \
    echo "hadoop ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user1

# 환경변수 세팅
ENV HADOOP_HOME=/home/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin
ENV PATH=$PATH:$HADOOP_HOME/sbin
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64

# 하둡 설치
COPY hadoop-3.4.1.tar.gz /hadoop-3.4.1.tar.gz
RUN tar -zxf hadoop-3.4.1.tar.gz && \
    mv hadoop-3.4.1/* $HADOOP_HOME && \
    rmdir hadoop-3.4.1 && \
    chown -R hadoop:hadoop $HADOOP_HOME && \
    rm hadoop-3.4.1.tar.gz

USER hadoop

# ssh 암호 세팅
RUN mkdir -p /home/hadoop/.ssh && \
    ssh-keygen -t rsa -f /home/hadoop/.ssh/id_rsa -P '' && \
    cat /home/hadoop/.ssh/id_rsa.pub >> /home/hadoop/.ssh/authorized_keys && \
    chmod 700 /home/hadoop/.ssh && \
    chmod 600 /home/hadoop/.ssh/authorized_keys && \
    echo "Host *\n  StrictHostKeyChecking no" > /home/hadoop/.ssh/config && \
    chmod 600 /home/hadoop/.ssh/config && \
    chown -R hadoop:hadoop /home/hadoop/.ssh

RUN echo "export JAVA_HOME=$JAVA_HOME" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh; \
    echo "export HDFS_NAMENODE_USER=hadoop" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh; \
    echo "export HDFS_DATANODE_USER=hadoop" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh; \
    echo "export HDFS_SECONDARYNAMENODE_USER=hadoop" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh;\
    echo "export YARN_RESOURCEMANAGER_USER=hadoop" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh; \
    echo "export YARN_NODEMANAGER_USER=hadoop" >> $HADOOP_HOME/etc/hadoop/hadoop-env.sh;

COPY core-site.xml $HADOOP_HOME/etc/hadoop/core-site.xml
COPY hdfs-site.xml $HADOOP_HOME/etc/hadoop/hdfs-site.xml
COPY mapred-site.xml $HADOOP_HOME/etc/hadoop/mapred-site.xml
COPY yarn-site.xml $HADOOP_HOME/etc/hadoop/yarn-site.xml