export JAVA_HOME=${JAVA_HOME}
export PYSPARK_PYTHON=$(which python)

export SPARK_HOME=${SPARK_HOME:-/usr/local/spark}

export SPARK_MASTER_HOST=${SPARK_MASTER_HOST:-spark-master}
export SPARK_MASTER_PORT=${SPARK_MASTER_PORT:-7077}
export SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT:-8080}

export SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-4}
export SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-1g}
export SPARK_WORKER_PORT=${SPARK_WORKER_PORT:-7078}
export SPARK_WORKER_WEBUI_PORT=${SPARK_WORKER_WEBUI_PORT:-8081}